name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ "dev", "main" ]
    paths:
      - 'api/**'
      - 'web/**'
      - '.github/**'
      - 'Dockerfile'
      - 'docker-compose.yaml'
      - 'README.md'
    tags:
      - 'v*'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'api/**'
      - 'web/**'
      - '.github/**'
      - 'Dockerfile'
      - 'docker-compose.yaml'
      - 'README.md'

jobs:
  build-check:
    name: Build Check
    runs-on: 'ubuntu-24.04'
    timeout-minutes: 60
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Cache tdlib and config
        id: cache-tdlib
        uses: actions/cache@v4
        with:
          path: |
            ../libs
            ../.env.test
          key: ${{ runner.os }}-tdlib-1.15.0

      - name: Download tdlib and create .env.test file
        if: steps.cache-tdlib.outputs.cache-hit != 'true'
        run: |
          cd ../ && \
          wget --no-check-certificate -q -O libs.zip https://github.com/p-vorobyev/spring-boot-starter-telegram/releases/download/1.15.0/libs.zip && \
          unzip -q libs.zip && \
          cat <<EOF > .env.test
          TDLIB_PATH=../libs/linux_x64
          APP_ENV=prod
          APP_ROOT=${{ github.workspace }}/data
          TELEGRAM_API_ID=94575
          TELEGRAM_API_HASH=a3406de8d171bb422bb6ddf3bbd800e2
          LOG_LEVEL=FINE
          EOF

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

  build-docker:
    name: Build and Push Docker Image
    needs: build-check
    if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/telegram-files
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
